export const click = 'click'
export const input = 'input'
export const navItems = ['STATISTIC', 'BASIC RULES', 'DEFINITION']
export const statisticHeadLine = navItems[0]
export const sliderIntervals = ['FAST', 'MEDIUM', 'SLOW']
export const playIcon = 'fa-play-circle-o'
export const stopIcon = 'fa-pause-circle-o'
export const resetIcon = 'fa-refresh'
export const settingIcon = 'fa-cog'
export const iconAssets = ['fa', 'fa-3x']
export const statisticDescriptions = ['Generation:', 'Overall living Cells:', 'Death by Overpolulation:', 'Death by Underpopulation:', 'Resurrection by Reproduction:']
export const settingsLabel = 'Interval Speed between Evolution'